server:
  port: 8080
  servlet:
    context-path: /shjz

spring:
  application:
    name: shjz-server
  banner:
    location: banner.txt
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据库连接配置
      url: jdbc:mysql://localhost:3306/shjz?useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 12345678
      ## 连接池配置
      ## 初始化大小，最大数量，最小数量
      initial-size: 10
      max-active: 50
      min-idle: 10
      ## 连接超时时间
      max-wait: 60000
      ## 检测空闲连接的时间间隔配置，决定是否关闭连接，单位为毫秒
      time-between-eviction-runs-millis: 60000
      ## 连接的最小空闲时间，单位为毫秒
      min-evictable-idle-time-millis: 300000
      ## 检测连接是否有效的 SQL
      validation-query: SELECT 1
      validation-query-timeout: 3000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      ## 配置 PSCache，配置每个连接 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      ## 监控 filter 配置，如果删除该配置，sql 监控将失效，使用 wall 配置防火墙
      filters: config,stat,wall,slf4j
      # sql 监控
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: true
      # WebStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*
        session-stat-enable: true
        profile-enable: true
      # StatViewServlet
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 12345678
      # spring 监控
      aop-patterns: com.myspace.serve.*
  # liquibase 配置
  liquibase:
    enabled: true
#    check-change-log-location: true # 检测 log 文件是否存在
    change-log: classpath:liquibase/master.xml # log 文件位置
    drop-first: false # 是否删除数据库
  # jackson
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    password: 12345678
    jedis:
      pool:
        max-wait: -1
        min-idle: 10
        max-idle: 50
        max-active: 50
    port: 6379

id-worker:
  worker-id: 1
  data-center-id: 1

token:
  jwt:
    key: zp95sky
    iss: 11
    # token 有效期，单位：分钟
    expm: 1440

management:
  endpoints:
    web:
      exposure:
        include: '*'